version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: fly_project
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bd71147332
